<template>
  <div class="ldio-dc0w7x539qd flex justify-center">
    <div></div>
  </div>
</template>

<style type="text/css">
@keyframes ldio-dc0w7x539qd {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-dc0w7x539qd div {
  position: absolute;
  width: 1rem;
  height: 1rem;
  border: 4px solid #050505;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-dc0w7x539qd div {
  animation: ldio-dc0w7x539qd 1s linear infinite;
}
.ldio-dc0w7x539qd {
  width: 100%;
  height: 100%;
  padding: 0.73rem;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-dc0w7x539qd div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
